version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: eslint
    versions:
    - 7.17.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: redis
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: faker
    versions:
    - 5.1.0
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: husky
    versions:
    - 4.3.7
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: socket.io
    versions:
    - 3.0.5
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: socket.io-redis
    versions:
    - 6.0.1
  registries:
  - npm-registry-npm-pkg-github-com
  - git-github-com
