version: 2

jobs:
  checkout_code:
    working_directory: /home/circleci/generic-redis-cache

    docker:
      - image: circleci/node:10.18

    steps:
      - checkout

      - save_cache:
          key   : repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths :
            - ./

  node_dependencies:
    working_directory: /home/circleci/generic-redis-cache

    docker:
      - image: circleci/node:10.18

    steps:
      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name    : Authenticating with github registry
          command : npm config set '//npm.pkg.github.com/:_authToken' "${NPM_GITHUB_TOKEN}"

      - run:
          name    : Installing npm dependencies
          command : npm install

      - save_cache:
          key   : node-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths :
            - ./node_modules

  tests:
    working_directory: /home/circleci/generic-redis-cache

    docker:
      - image: circleci/node:10.18

      - image: redislabs/rejson:latest

    steps:

      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name    : Waiting for Redis
          command : dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          name    : Running tests
          command : npm run test

      - store_artifacts:
          path    : test-results.xml
          prefix  : tests

      - store_artifacts:
          path    : coverage
          prefix  : coverage

      - store_test_results:
          path: test-results.xml

      - save_cache:
          key   : test-coverage-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths : ./coverage

  npm_version:
      working_directory: /home/circleci/users

      docker:
        - image: circleci/node:10.18

      steps:
        - restore_cache:
            key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

        - restore_cache:
            key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

        - run:
            name    : Updating version
            command : npm run update-version

  npm_release:
    working_directory: /home/circleci/users

    docker:
      - image: circleci/node:10.18

    steps:
      - restore_cache:
          key: repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          key: node-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name    : Authenticating with registry
          command : |
            echo "registry=https://npm.pkg.github.com/contartec-team" > .npmrc
            echo "//npm.pkg.github.com/:_authToken=$NPM_GITHUB_TOKEN" >> .npmrc

      - run:
          name    : Releasing and publishing version
          command : npm run release-version

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code

      - node_dependencies:
          requires:
            - checkout_code

      - tests:
          requires:
            - node_dependencies

      - approval:
          filters:
            branches:
              ignore: master
          type: approval
          requires:
            - tests

      - npm_version:
          requires:
            - approval

      - npm_release:
          filters:
            branches:
              only: master
          requires:
            - tests